# -*- coding: utf-8 -*-
"""image2vector.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PMUPiAfowWxOj5023FsRQwN4AU4cRxz5
"""

!git clone https://github.com/drkhurramiqbal26iu/corvit_project.git

import fileinput

file_path = '/content/corvit_project/image2vector.py'
old_line = 'image.show()'
new_line = '# image.show()  # Commented out for Colab environment'

with fileinput.FileInput(file_path, inplace=True) as file:
    for line in file:
        print(line.replace(old_line, new_line), end='')

print(f"Successfully commented out 'image.show()' in {file_path}.")

from google.colab import drive
drive.mount('/content/drive')

!python corvit_project/image2vector.py

import fileinput

file_path = '/content/corvit_project/image2vector.py'
old_line = 'image = Image.open("/content/cat.jpg")'
new_line = 'image = Image.open("/content/corvit_project/cat.jpg")'

with fileinput.FileInput(file_path, inplace=True) as file:
    for line in file:
        print(line.replace(old_line, new_line), end='')

print(f"Successfully updated {file_path} to correct image path.")